### ISSUE TITLE
MTU needs to be set smaller for reliable SSH

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#20]
I just spent an hour chasing a problem that boiled down to the notorious "ssh hangs exchanging hostkeys" issue. This seems to be due to a combination of factors:
1. a big message to/from the server
2. MTU set to 1500 on the local eth0 interface
3. a path MTU that is actually somewhat less than 1400
4. a combination of NATing and VPNing and firewalling that results in the path MTU discovery packets getting dropped.

This will happen from time to time. I think the best solution is to drop the MTU to about 1100. This must be done with a post-up operation in `/etc/network/interfaces`:
- `post-up ifconfig eth0 mtu 1100`

I've done this in my pre-ansible setup, will also change roles/conduit/templates/interfaces.j2 (as this doesn't want to get hammered during final deployment).

**Comment by jchonig** [comment]
Fixed this with [this commit](https://github.com/IthacaThings/ttn-multitech-cm/commit/dba37139a205e4ab7b6d514bdec19e7ced753d90)
