### ISSUE TITLE
Error messages for failures are tough for non-experts

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#22]
If `make apply` fails, the failure is somewhat sticky.

You get messages that refer to the Ansible command line, namely:
```
to retry, use: --limit @/home/tmm/sandbox/org-ttnnyc-gateways/ttn-multitech-cm/site.retry
```
But there's no good way to get that into the make command line.

Perhaps an arg like: "RETRY=1" to add the argument? I'll experiment.

**Comment by jchonig** [comment]
TARGET=@site.retry will do this as TARGET is really about -l options.

I think it would be useful to have 'make retry' and 'make apply-debug'.

**Comment by jchonig** [comment]
I added 'make retry' in d627e4471b2026897d93d678251445359ecc92d7
