### ISSUE TITLE
Need a way to supply debug flags from command line

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#23]
Hard to get the -vvv that's sometimes needed into the Makefile.

Suggest an extra variable `PLAYBOOK_FLAGS_USER` that can be set from the command line.

**Comment by jchonig** [comment]
I added 'make apply-debug' and 'make test-debug'.  I also added OPTIONS= keyword.  All in d627e4471b2026897d93d678251445359ecc92d7
