### ISSUE TITLE
Use `-u` with ntpdate

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#26]
The script tries to call ntpdate to set the date. It does this without the `-u` option. This means that it fails if NTPD is running.

It will be less alarming for users if the `-u` switch is used; this will use a port above 1024 to send the NTP requests, and works well (I use it all the time in my NetBSD VMs because the NTP daemon is too slow to get the time corrected when errors are big, and NetBSD and VMware don't do a great job on time).

(Might also consider using `-b`, which causes the time to just be reset, no skewing. We're not running a time critical service at the moment of ntpdate, so it's more effective to just reset the clock.)

**Comment by jchonig** [comment]
Fixed in 80655c31107d53ed23dbbd397c540e2b7640663a
