### ISSUE TITLE
No module named grp error when running ansible command

### ISSUE THREAD

**Issue by ddewaele** [IthacaThings/ttn-multitech-cm#30]
Got the following error when running a simple ansible command targetting the multitech 

```
ansible -m ping all


multitech1 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Shared connection to 192.168.2.1 closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_g4ngnU/ansible_module_ping.py\", line 60, in <module>\r\n    from ansible.module_utils.basic import AnsibleModule\r\n  File \"/tmp/ansible_g4ngnU/ansible_modlib.zip/ansible/module_utils/basic.py\", line 83, in <module>\r\nImportError: No module named grp\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

On the MultitTech I had done this  : 
```
admin@mtcdt:~# opkg update
Downloading http://multitech.net/mlinux/feeds/3.3.12/all/Packages.gz.
Inflating http://multitech.net/mlinux/feeds/3.3.12/all/Packages.gz.
Updated list of available packages in /var/lib/opkg/mlinux-all.
Downloading http://multitech.net/mlinux/feeds/3.3.12/arm926ejste/Packages.gz.
Inflating http://multitech.net/mlinux/feeds/3.3.12/arm926ejste/Packages.gz.
Updated list of available packages in /var/lib/opkg/mlinux-arm926ejste.
Downloading http://multitech.net/mlinux/feeds/3.3.12/mtcdt/Packages.gz.
Inflating http://multitech.net/mlinux/feeds/3.3.12/mtcdt/Packages.gz.
Updated list of available packages in /var/lib/opkg/mlinux-mtcdt.

admin@mtcdt:~# opkg install python-pkgutil
Installing python-pkgutil (2.7.3-r0.3.0) to root...
Downloading http://multitech.net/mlinux/feeds/3.3.12/arm926ejste/python-pkgutil_2.7.3-r0.3.0_arm926ejste.ipk.
Configuring python-pkgutil.
admin@mtcdt:~# opkg install python-distutils
Installing python-distutils (2.7.3-r0.3.0) to root...
Downloading http://multitech.net/mlinux/feeds/3.3.12/arm926ejste/python-distutils_2.7.3-r0.3.0_arm926ejste.ipk.
Configuring python-distutils.
```

Indeed, the module is missing on the conduit : 
```
admin@mtcdt:~# python
Python 2.7.3 (default, Jun  5 2017, 08:47:27) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import grp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named grp
>>> 
```

Any ideas ?

**Comment by jchonig** [comment]
What version of mLinux are you using?

Which version of Ansible?

On my 3.3.13 Conduit I have:

```
ttn-ith-test:~$ python
Python 2.7.3 (default, Sep 20 2017, 12:39:35)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import grp
>>>
```

**Comment by ddewaele** [comment]
It's a Conduit mLinux version (210L) that was Flashed to AEP 1.4.3

```
admin@mtcdt:/# uname -a
Linux mtcdt 3.12.27r13 #1 PREEMPT Mon Jun 5 08:39:04 CDT 2017 armv5tejl GNU/Linux
```

However the `/etc/opkg/mlinux-feed.conf` contained the following (3.3)
```
src/gz mlinux-all http://multitech.net/mlinux/feeds/3.3/all
src/gz mlinux-arm926ejste http://multitech.net/mlinux/feeds/3.3/arm926ejste
src/gz mlinux-mtcdt http://multitech.net/mlinux/feeds/3.3/mtcdt
```

But since there is no http://multitech.net/mlinux/feeds/3.3 I changed the 3.3 references to 3.3.12

The version of ansible : 

```
[root@centosansible lib-dynload]# ansible --version
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

**Comment by jchonig** [comment]
That's a bug in mlinux-feed.conf which they have fixed in mLinux.

I would be careful running this against AEP, I haven't looked at the differences and it may make a mess of things.

A quick google shows that grp should be available in python-unixadmin:
`ttn-ith-test:/home/ttn# opkg list | grep python-unixadmin
python-unixadmin - 2.7.3-r0.3.0 - Python Unix administration support  The Python Programming Language.`

**Comment by ddewaele** [comment]
You have superior Google skills :) Not very familiar with python, found a lot of stuff on grp but not in what package it resides.  (how do you find out in what opkg package the grp module resides?)

But basic ansible communication is now up and running with this module installed.

Thx !

**Comment by jchonig** [comment]
mLinux is based on the Yocto Project so I figured it was a Yocto Project
packaging issue.  So I Google python grp and Yocto Project and found this
<https://git.yoctoproject.org/cgit.cgi/poky/plain/meta/recipes-devtools/python/python-2.7-manifest.inc>
which
shows that the grp module is in the unixadmin package:=

> SUMMARY_${PN}-unixadmin="Python Unix administration support"
> RDEPENDS_${PN}-unixadmin="${PN}-core"
> FILES_${PN}-unixadmin=" \
>     ${libdir}/python2.7/lib-dynload/nis.so \
>     ${libdir}/python2.7/lib-dynload/grp.so \
>     ${libdir}/python2.7/lib-dynload/pwd.so \
>     ${libdir}/python2.7/getpass.* \
> "
>
>
Thanks

Jeff

-- 
Jeffrey C. Honig <jch@honig.net>
http://jch.honig.net
GnuPG ID:14E29E13 <http://jch.honig.net/Home/pgp_key>
Keybase: jchonig <https://keybase.io/jchonig>
