### ISSUE TITLE
Add ability to put org-specific info (catalog, database, etc.) outside this repo 

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#33]
Right now, the suggested model is to create a branch to contain the info for your orgs repos. But the style suggested by https://github.com/terrillmoore/conduit-mfg is to use a separate repo. It's easy to support both by allowing the makefile to autodetect the setup. A suggested patch is forthcoming.

**Comment by jchonig** [comment]
Integrated your fixes
