### ISSUE TITLE
Don't use -M 0 for ssh tunnels

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#38]
It seems that trying to use autossh without -M {baseport} doesn't work well. The tunnels don't detect failure nearly often enough.

The solution is to use a keepalive port. However, one needs a strategy for keeping the baseport out of the way. The solution we propose is to set keepalive_baseport = 40000 + 2 * ( tunnelport - 20000 ).

(Of course, 40000 and 20000 are parameters in the script that actually generates these on the jumphost, `conduit-stage2`)

**Comment by jchonig** [comment]
Will be fixed by commit master 6c50e2fcbd246270747d9e78a59686060730ab80
