### ISSUE TITLE
Lora packet forwarder logs are not rotated

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#41]
The lora packet forwarder logs are not rotated, and so can fill /var/volatile. This is not great when it happens.

**Comment by jchonig** [comment]
Requested a signal to rotate the log file from [mp_packet_forwarder](https://github.com/kersing/packet_forwarder/issues/13).  In the meantime I'll implement this as a restart.

**Comment by jchonig** [comment]
Testing overnight

**Comment by jchonig** [comment]
Works in master
