### ISSUE TITLE
Incorrect JSON syntax in /var/config/local/local_conf.json

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#43]
The scripts generate incorrect json data.

Here's what's generated:
```json
/* Generated via Ansible */
{
    "gateway_conf": {
        "gateway_ID": "00800000A0000EDF",
        "contact_email": "tmm@mcci.com",
        "description": "Dan Lavin",
        "gps": true,
        "fake_gps": true,
        "ref_latitude": 40.7329302,
        "ref_longitude": -74.0061403,
        "ref_altitude": 16,
    }
}
```
1. The comment is not permitted
2. the dangling comma after ref_altitude is not allowed.

This should be:
```json
{
    "gateway_conf": {
        "gateway_ID": "00800000A0000EDF",
        "contact_email": "tmm@mcci.com",
        "description": "Dan Lavin",
        "gps": true,
        "fake_gps": true,
        "ref_latitude": 40.7329302,
        "ref_longitude": -74.0061403,
        "ref_altitude": 16
    }
}
```

**Comment by jchonig** [comment]
The packet forwarder ignores the comment.  I found and fixed the later last night.

**Comment by terrillmoore** [comment]
Please consider generating legal JSON. The [official spec for JSON](json.org/) doesn't allow comments.  See [https://justin.kelly.org.au/comments-in-json/](this discussion) for alternatives.

**Comment by jchonig** [comment]
Resolved by commit https://github.com/IthacaThings/ttn-multitech-cm/commit/748f3cfb7d8ddb18bd9e98f7e10d0990989a931e
