### ISSUE TITLE
Additional packages are required if running the MultiTech base image

### ISSUE THREAD

**Issue by jchonig** [IthacaThings/ttn-multitech-cm#50]
@Tombar reports that additional packages are required when running the mLinux base image.

python-netclient brings in base64, needed for Ansible to run
node for ttn
libmpsse for ttn
autossh for ssh_tunnel.

Add these packages to the right place (doc, tasks modules). @

**Comment by jchonig** [comment]
Try installing mlinux-base image and see what packages are required to run.

**Comment by terrillmoore** [comment]
For clarity, is "mlinux base image" the image distributed by Multitech? (As opposed to the IthacaThings image?) [It will probably help future people searching for solutions...]

**Comment by Tombar** [comment]
@terrillmoore YES, if installing mlinux base image distributed by Multitech, there are some more packages missing than the ones listed in the readme.

From my notes:

```
opkg update
opkg instsall python
  python-async \
  python-argparse \
  python-compression \
  python-dateutil \
  python-html \
  python-psutil \
  python-pycurl \
  python-pyopenssl \
  python-pyserial \
  python-pyudev \
  python-pyusb \
  python-simplejson \
  python-syslog \
  python-textutils \
  python-unixadmin \
  python-xml \
  python-distutils \
  python-json \
  python-pkgutil \
  python-shell
opkg install node
opkg install autossh
opkg install libmpsse
```

**Comment by jchonig** [comment]
I've integrated these into Ansible in the appropriate place and am updating the docs.
