### ISSUE TITLE
Running `make TARGET=x ping` creates a directory called `$CATALOG`

### ISSUE THREAD

**Issue by frankleonrose** [IthacaThings/ttn-multitech-cm#57]
After poking around a bit, I suspect that `$VARIABLES` are not supported in the file 'ansible.cfg'.

**Comment by jchonig** [comment]
This is a Makefile bug, I do not set CATALOG for the ping and some other targets.

**Comment by jchonig** [comment]
Fixed by https://github.com/IthacaThings/ttn-multitech-cm/commit/ab5dadb9e1fa966694348d5d726ae13e834575ce

**Comment by frankleonrose** [comment]
@jchonig Thanks!
