### ISSUE TITLE
Prior to mp packet forwarder 3.0.20-r1 autoquit_threshold is required

### ISSUE THREAD

**Issue by jchonig** [IthacaThings/ttn-multitech-cm#61]
> From #ops: @terrillmoore If you add an "autoquit_threshold" to the "gateway_conf" section of the packer forwarder config then it will auto-quit after that many missed PULL_ACKs. It works well with systemd or the like, which can then start the packet forwarder again. 20 seems to work alright on LTE connections here, that periodically die and break things

**Comment by jchonig** [comment]
Adding **autoquit_threshold** will cause the packet forwarder to quit.  However without systemd and/or monit, it will not restart by itself.

**Comment by terrillmoore** [comment]
And, for what it's worth, we have not demonstrated that `autoquit_threshold` actually detects the situation. I agree that the best solution is to update the older gateways to use 3.0.20-r1.
