### ISSUE TITLE
make apply fails with /usr/local/lib not found

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#69]
I had a gateway which had been roughly through the following history:

1. initialize (using mainline of six months ago)
2. hack to connect to myDevices
3. install mlinux 3.3.24 (also six months ago, manually)
4. leave it sit
5. pull it out and notice that it was booting, but wasn't initialized. Apart from the stashed copies of the host keys in /var/config (and the corresponding links in /etc), it looked pristine; no scripts for launching the jumphost connection, no packet forwarder scripts, etc.
6. Manually get the jumphost connection running 
7. `make ping` works
8. `make apply` fails: [failure.log](https://github.com/IthacaThings/ttn-multitech-cm/files/4561862/failure.log)
9. manually confirm that there's no /usr/local/lib; manually `mkdir /usr/local/lib`
10. `make apply` succeeds.

**Comment by terrillmoore** [comment]
Here's the error message:

```log
TASK [conduit : Install monit test scripts] ************************************
failed: [ttn-ithaca-00-08-00-4a-3f-8a] (item=check_pktfwdlog) => {"ansible_loop_var": "item", "changed": false, "checksum": "7de8a76ac28e5f0d7e43fb3ca5b21df01f4fb303", "item": "check_pktfwdlog", "msg": "Destination directory /usr/local/lib does not exist"}
failed: [ttn-ithaca-00-08-00-4a-3f-8a] (item=check_system_md5) => {"ansible_loop_var": "item", "changed": false, "checksum": "354fc415b2b6b11cc81c07e6cc155df8c1dd8cd3", "item": "check_system_md5", "msg": "Destination directory /usr/local/lib does not exist"}
```

Here's what's in /usr/local:

```console
root@ttn-ithaca-00-08-00-4a-3f-8a:~# ls /usr/local/
share
root@ttn-ithaca-00-08-00-4a-3f-8a:~# cat /etc/mlinux-version
mLinux 3.3.24
Built from branch: (detachedfrom630d62a)
Revision: 630d62a4443465a194ec642aba537e7796d9eb3d
root@ttn-ithaca-00-08-00-4a-3f-8a:~#
```

Precondition: update to mlinux 3.3.24 (in the field). For some reason, the gateway update didn't take (although /var/config existed, the ssh_tunnel components were missing). Manually install and get the ssh tunnel working. Do a make apply; install python-multiprocessing after make apply failed. make apply again.

**Comment by jchonig** [comment]
I had assumed that /usr/local existed in the base image.  But it does not.  It automatically gets created when we install letsencrypt certificates.

I've updated the code handle this situation.
