### ISSUE TITLE
bin/register does not work with old python 3.6

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#71]
`bin/register` won't run on Python 3.6, but works with Python 2.7.  My new system already had Python3 installed and the default version is Python3.

Changing the first line to:

```python
#!/usr/bin/env python2
```

solves the problem. Note, however, that Python 2.7 is end of life.  (I was testing on the `auto_restart` branch.)

**Comment by jchonig** [comment]
This script was updated to work with both python2 and python3.  What's the specific error?

**Comment by terrillmoore** [comment]
Was it updated on the branch? It’s a failure in an unsupported method in subprocess:

 

```

fatal: [ttn-nyc-00-08-00-4a-e0-5c -> localhost]: FAILED! => {"changed": true, "cmd": "bin/register --json --id ttn-nyc-00-08-00-4a-e0-5c --region US --latitude 40.734905 --longitude -73.820396 --router ttn-router-us-west --description 'Beeler Lab #1' --brand MultiTech --model MTCDT-246A --antenna-type '3.0dBi Rubber Duck' --antenna-model 'MultiTech AN868-915A-1HRA' --old_id eui-00800000a0005bfe --collaborators '[{\"username\": \"jchonig\"}, {\"username\": \"terrillmoore\"}, {\"username\": \"cvb-mcci\"}, {\"username\": \"beelerlab\"}]'", "delta": "0:00:00.111662", "end": "2021-02-08 07:17:08.870251", "msg": "non-zero return code", "rc": 1, "start": "2021-02-08 07:17:08.758589", "stderr": "Traceback (most recent call last):\n  File \"bin/register\", line 489, in <module>\n    sys.exit(main())\n  File \"bin/register\", line 445, in main\n    gateways = ttn_gateway_list(options)\n  File \"bin/register\", line 282, in ttn_gateway_list\n    lines = check_output(options, cmd)\n  File \"bin/register\", line 318, in check_output\n    output = subprocess.check_output(cmd, text=True)\n  File \"/usr/lib/python3.6/subprocess.py\", line 356, in check_output\n    **kwargs).stdout\n  File \"/usr/lib/python3.6/subprocess.py\", line 423, in run\n    with Popen(*popenargs, **kwargs) as process:\nTypeError: __init__() got an unexpected keyword argument 'text'", "stderr_lines": ["Traceback (most recent call last):", "  File \"bin/register\", line 489, in <module>", "    sys.exit(main())", "  File \"bin/register\", line 445, in main", "    gateways = ttn_gateway_list(options)", "  File \"bin/register\", line 282, in ttn_gateway_list", "    lines = check_output(options, cmd)", "  File \"bin/register\", line 318, in check_output", "    output = subprocess.check_output(cmd, text=True)", "  File \"/usr/lib/python3.6/subprocess.py\", line 356, in check_output", "    **kwargs).stdout", "  File \"/usr/lib/python3.6/subprocess.py\", line 423, in run", "    with Popen(*popenargs, **kwargs) as process:", "TypeError: __init__() got an unexpected keyword argument 'text'"], "stdout": "", "stdout_lines": []}

```

**Comment by jchonig** [comment]
This was done long ago.

This is just something I missed, or python3 deprecated the argument I was
using.

Thanks

Jeff

-- 
Jeffrey C. Honig <jch@honig.net>
http://jch.honig.net
PGP ID: A96C148E8B0E5F741A90ED04BBE5FFC5E52718CE
<https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xa96c148e8b0e5f741a90ed04bbe5ffc5e52718ce>
Keybase: jchonig <https://keybase.io/jchonig>
Secure E-mail <https://protonmail.com>: jchonig@pm.me

**Comment by terrillmoore** [comment]
Do I need to cherry-pick a change, or send a pull-request, or...?  How should I proceed?

**Comment by terrillmoore** [comment]
By the way, on my other system, because python2 happens to be the default for python, there's no problem. The issue cropped up because the new system has python3 as the default (and I can't change that for other reasons).

**Comment by jchonig** [comment]
II'l try to figure out a python2 and 3 compatible fix in the next day or
two.

Thanks

Jeff

-- 
Jeffrey C. Honig <jch@honig.net>
http://jch.honig.net
PGP ID: A96C148E8B0E5F741A90ED04BBE5FFC5E52718CE
<https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xa96c148e8b0e5f741a90ed04bbe5ffc5e52718ce>
Keybase: jchonig <https://keybase.io/jchonig>
Secure E-mail <https://protonmail.com>: jchonig@pm.me

**Comment by jchonig** [comment]
I have an explicit check for python 3 in that code.  The problem is actually the old version of python 3 you are running.  3.6 is EOL at the end of this year.
