### ISSUE TITLE
mp-packet-forwarder_3.0.20-r1 is obsolete

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#72]
The code references "https://github.com/kersing/multitech-installer/raw/master/mp-packet-forwarder_3.0.20-r1_arm926ejste.ipk" to download the packet forwarder.

Unfortunately, this link is now broken.

Actually it was broken as of 2020, but I never noticed because the scripts look for, and use, a local copy.

Three action items (the Spanish Inquisition, etc.):

* we should put a copy of the official 3.0.20-r1 someplace safe (maybe with mlinux stuff?). 
* the scripts should refer to the safe place
* we need to consider updating to 3.0.25-r2 (which is current)

**Comment by jchonig** [comment]
3.0.25 no longer needs node as it no longer applies the multiech overrides.

**Comment by jchonig** [comment]
Fixed somewhere along the way to the current master.
