### ISSUE TITLE
main.yml `Set hostname` fails if `/etc/hostname` is already a symlink

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#73]
When setting hostname, we use the following:

https://github.com/IthacaThings/ttn-multitech-cm/blob/7707e6db0b7d7ea36f971891786b3e488d07e5fb/roles/conduit/tasks/main.yml#L60-L74

But if I read this correctly, this will fail if `/etc/hostname` is already linked to `/var/config/hostname`. I think it replaces the link with a file, which then gets hammered later on when the symlink farm to /var/config is re-established (re-establishing the old content). I *think* restoring /var/config/hostname symlink is a function of the mlinux distribution; I don't see where we do that, but it's clear that it's happening.

It doesn't always happen, which is odd; but if you try to fix things using `TAGS=hostname`, the wrong thing happens (as described) and so things don't get fixed.

Manual workaround is to restore the link by hand and then update `/var/config/hostname`.

**Comment by jchonig** [comment]
We restore symlinks with the *preserve* package which I bake into our image at image build time.   So this should only happen with our image.  If it happens in their image, that's something new.

**Comment by terrillmoore** [comment]
All I can report is when I want from mPower to V3.3.24, it happened on one of the two gateways. I can't explain it, just reporting. It happened on a couple of other gateways when I updated manually from V3.3.13 to V3.3.24 (not using Ansible), then ran Make Apply. So I think the rules sholuld be looking for the symlink or else putting the hostname in /var/config/hostname and establishing the symlink.

**Comment by jchonig** [comment]
Hmm, I already had a branch for this: https://github.com/IthacaThings/ttn-multitech-cm/compare/hostname

**Comment by jchonig** [comment]
The latest master branch should have a fix for this.
