### ISSUE TITLE
Default for gps_device is wrong for newer mLinux

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#85]
This changed at mLinux 4; we really aren't doing anything with mLinux 3 any more except to upgrade to newer versions.

Perhaps we should just change `roles/conduit/defaults/main.yml`::`gps_device` to  `gps0`?

**Comment by jchonig** [comment]
Fixed by https://github.com/IthacaThings/ttn-multitech-cm/commit/fb89fc91ae3cc9030994902e0eb9789007cda28f
