### ISSUE TITLE
monit spawns lots of pppd instances if sim card is slow to come up

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#88]
It doesn't look as if monit tries to kill the old pppd before trying to bring up another instance. pppd can be legitimately slow to start if the SIM card is registering (with the ones I use, first registration can take 5 minutes).

```console
root@ttn-ithaca-00-08-00-4c-11-de:~# ps waux | grep pppd
root      1163  0.0  0.6   5640  1608 ?        Ss   19:49   0:00 /usr/sbin/pppd call gsm
root      1373  0.0  0.6   5640  1700 ttyUSB2  Ss+  19:50   0:00 /usr/sbin/pppd call gsm
root      1419  0.0  0.6   5640  1588 ?        Ss   19:51   0:00 /usr/sbin/pppd call gsm
root      1494  0.0  0.6   5640  1640 ?        Ss   19:52   0:00 /usr/sbin/pppd call gsm
root      1546  0.0  0.8   5640  2060 ?        Ss   19:53   0:00 /usr/sbin/pppd call gsm
root      1574  0.0  0.6   3704  1696 pts/0    S+   19:55   0:00 grep pppd
root@ttn-ithaca-00-08-00-4c-11-de:~#
```
Note that the start times are separated by one minute. Once pppd brings the link up, monit stops trying to spawn ppp instances.

The fix is probably to just try to kill `/usr/sbin/ppdd` before restarting ppp; or else do a `/etc/init.d/ppp restart` (which also ought to clean things up). But starting ppp while another instance is running is a problem.

**Comment by jchonig** [comment]
The issue is that pppd does not create it's pid file until the connection is up.  So monit doesn't know it's actually running.

The fix is to use the MATCHING rule.
