### ISSUE TITLE
roles/conduit/templates/local_conf.json.j2 has typo

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#89]
Due to a typo in my original slack, there's an error in local_conf.json.j2 on the ttnv3 branch:
https://github.com/IthacaThings/ttn-multitech-cm/blob/fb89fc91ae3cc9030994902e0eb9789007cda28f/roles/conduit/templates/local_conf.json.j2#L6
Should be `cellular_keepalive_interval`, not ...`internval`.

**Comment by jchonig** [comment]
Fixed by https://github.com/IthacaThings/ttn-multitech-cm/commit/dbe3672bc270236629d89fb86bedcef829ef3107
