### ISSUE TITLE
Cellular (ppp) mlinux systems hang on boot if ethernet isn't connected

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#91]
`/etc/init.d/ppp` seems to be pre-installed with priority 20. This means it starts after `/etc/init.d/ntpd`.

Unfortunately, ntp seems to hang if Ethernet is not connected and up.

The provisional solution is to set the priority of `ppp` to `02`, so it starts after `networking` but before almost everything else.

This only affects `ttnv3` branch, and cellular systems.

**Comment by jchonig** [comment]
Upon further research, if we change _SET_SYSTEM_CLOCK_ to _0_ in **/etc/default/ntpd**, it will not run `ntpd -gq`, but instead start *ntpd* in the background with the *-g* flag which will allow it to step the clock the first time.  This should allow *ntpd* to run happily in the background while the init system continues to start processes.

**Comment by jchonig** [comment]
I tested this on a cellular gateway with no SIM installed and the system does not hang on ntp when _SET_SYSTEM_CLOCK_ is set to 0.

Writing up Ansible rules.

**Comment by jchonig** [comment]
Committed to *ttnv3* branch
